/* automatically generated by rust-bindgen 0.61.0 */

#![allow(dead_code)]

pub const FLASHMQ_PLUGIN_VERSION: u32 = 1;
pub const LOG_NONE: u32 = 0;
pub const LOG_INFO: u32 = 1;
pub const LOG_NOTICE: u32 = 2;
pub const LOG_WARNING: u32 = 4;
pub const LOG_ERR: u32 = 8;
pub const LOG_DEBUG: u32 = 16;
pub const LOG_SUBSCRIBE: u32 = 32;
pub const LOG_UNSUBSCRIBE: u32 = 64;
extern "C" {
    #[doc = " @brief flashmq_logf calls the internal logger of FlashMQ. The logger mutexes all access, so is thread-safe, and writes to disk"]
    #[doc = " asynchronously, so it won't hold you up."]
    #[doc = " @param level is any of the levels defined above, starting with LOG_."]
    #[doc = " @param str"]
    #[doc = ""]
    #[doc = " FlashMQ makes no distinction between INFO and NOTICE."]
    pub fn flashmq_logf(level: ::std::os::raw::c_int, str_: *const ::std::os::raw::c_char, ...);
}
